#!/usr/bin/env python3
"""Download the three design fonts as woff2 and emit a self-hosted @font-face file."""
import os
import re
import urllib.request

THEME = "/Users/mada/work/rartist/wp-theme/rartist"
FONT_DIR = os.path.join(THEME, "assets/fonts")
CSS_OUT = os.path.join(THEME, "assets/css/05-fonts.css")
UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"

FAMILIES = [
    ("Playfair Display", "Playfair+Display:wght@400;500"),
    ("Geist", "Geist:wght@400;500"),
    ("Geist Mono", "Geist+Mono:wght@400"),
]

os.makedirs(FONT_DIR, exist_ok=True)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


blocks = []
for label, spec in FAMILIES:
    css = fetch(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()
    # Keep only latin and latin-ext subsets; the design uses no other scripts.
    chunks = re.split(r"/\*\s*([\w\-\[\]]+)\s*\*/", css)
    keep = []
    for i in range(1, len(chunks), 2):
        subset, body = chunks[i], chunks[i + 1]
        if subset in ("latin", "latin-ext"):
            keep.append((subset, body))
    for subset, body in keep:
        for face in re.findall(r"@font-face\s*\{[^}]+\}", body):
            url = re.search(r"url\((https://[^)]+\.woff2)\)", face)
            weight = re.search(r"font-weight:\s*(\d+)", face)
            if not url:
                continue
            slug = label.lower().replace(" ", "-")
            name = f"{slug}-{weight.group(1) if weight else '400'}-{subset}.woff2"
            path = os.path.join(FONT_DIR, name)
            if not os.path.exists(path):
                with open(path, "wb") as f:
                    f.write(fetch(url.group(1)))
            face = face.replace(url.group(1), f"../fonts/{name}")
            face = re.sub(r"^\s+", "\t", face, flags=re.M)
            blocks.append(face.strip())

header = """/*
 * Self-hosted design fonts — Playfair Display (display), Geist (body), Geist Mono (caption).
 * Generated by scripts/fetch-fonts.py from the Google Fonts API; latin + latin-ext only.
 * No third-party requests at runtime.
 */
"""

with open(CSS_OUT, "w") as f:
    f.write(header + "\n" + "\n\n".join(blocks) + "\n")

print(f"{len(blocks)} @font-face blocks")
for name in sorted(os.listdir(FONT_DIR)):
    print("  ", name, f"{os.path.getsize(os.path.join(FONT_DIR, name)) // 1024}K")
